SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
FRAME_RATE = 60
BACKGROUND_COLOUR = (64, 64, 64)
ANIMATION_TICKS = 120
TEXT_TICKS = 600
LEVEL_ROWS = 150
LEVEL_COLS = 150
SCROLL_THRESHOLD = 200

IMAGE_SCALE = 3
TILE_SCALE = 5
ITEM_SCALE = 3
COIN_SCALE = 2.5
WEAPON_SCALE = 1.5
TILE_SIZE = 16 * TILE_SCALE
ITEM_SIZE = 16 * ITEM_SCALE
OFFSET = 8

ANIMATION_TYPES = ['idle', 'run']
CHARACTER_TYPES = ['big_demon', 'elf', 'goblin', 'imp', 'muddy', 'skeleton', 'tiny_zombie']
WEAPONS = ['arrow', 'bow', 'fireball']

MOVEMENT_SPEED = 5
MOB_SPEED = 4
SHOT_COOLDOWN = 300
SHOT_SPEED = 15
SHOT_DISTANCE = 30
MOB_ATTACK_COOLDOWN = 300
MOB_STUN_COOLDOWN = 200
ITEM_COIN = 0
ITEM_POTION = 1