SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FRAME_RATE = 60
BACKGROUND_COLOUR = (64, 64, 64)
ANIMATION_TICKS = 120
TEXT_TICKS = 600

IMAGE_SCALE = 3
ITEM_SCALE = 3
COIN_SCALE = 2.5
WEAPON_SCALE = 1.5
TILE_SIZE = 16 * IMAGE_SCALE
OFFSET = 10

ANIMATION_TYPES = ['idle', 'run']
CHARACTER_TYPES = ['big_demon', 'elf', 'goblin', 'imp', 'muddy', 'skeleton', 'tiny_zombie']
WEAPONS = ['arrow', 'bow', 'fireball']

MOVEMENT_SPEED = 5
SHOT_COOLDOWN = 300
SHOT_SPEED = 15
SHOT_DISTANCE = 30
ITEM_COIN = 0
ITEM_POTION = 1